version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INTERNAL_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_EXTERNAL_PORT: ${POSTGRES_EXTERNAL_PORT}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BACKEND_INTERNAL_PORT: ${BACKEND_INTERNAL_PORT}
      BACKEND_EXTERNAL_PORT: ${BACKEND_EXTERNAL_PORT}
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_API_URL: ${REACT_APP_BACKEND_API_URL}
      FRONTEND_INTERNAL_PORT: ${FRONTEND_INTERNAL_PORT}
      FRONTEND_EXTERNAL_PORT: ${FRONTEND_EXTERNAL_PORT}
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}"
    depends_on:
      - backend

volumes:
  pgdata:

