name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory and list files
        run: |
          pwd
          ls -la

      - name: Load environment variables
        run: |
          set -a
          source .env.example
          set +a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d --build
          sleep 30

      - name: Check running containers
        run: docker ps
