name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename env vars file
        run: mv .env.vars .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d --build
          sleep 30

      - name: Check running containers
        run: docker ps
