name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: task_manager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: mypassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the docker-compose stack
        run: docker-compose up --wait --wait-timeout 30

      - name: Check running containers
        run: docker ps
