name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build-backend:
    name: Build and Test Backend (bare-metal)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install Dependencies
        run: npm install
        working-directory: ./backend
  
      - name: Run Tests
        run: npm test
        working-directory: ./backend
        
  build:
    name: Build Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename env vars file
        run: mv .env.example .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d --build
          sleep 30

      - name: Check running containers
        run: docker ps

