name: Create branch and push to Docker Hub on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build and push to Docker Hub with release tag
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Postgres Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_PROJECT }}:postgres-${{ github.event.release.tag_name }} ./postgres

    - name: Build Backend Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_PROJECT }}:backend-${{ github.event.release.tag_name }} ./backend

    - name: Build Frontend Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_PROJECT }}:frontend-${{ github.event.release.tag_name }} ./frontend

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.event_name == 'push'
      run: |
        docker push ${{ vars.DOCKERHUB_PROJECT }}:postgres-${{ github.event.release.tag_name }}
        docker push ${{ vars.DOCKERHUB_PROJECT }}:backend-${{ github.event.release.tag_name }}
        docker push ${{ vars.DOCKERHUB_PROJECT }}:frontend-${{ github.event.release.tag_name }}

  create_branch:    
    name: Create branch with release tag
    runs-on: ubuntu-latest
    steps:
        - name: Create a new branch
          run: |
            BRANCH_NAME="release-${{ github.event.release.tag_name }}"
            git checkout -b $BRANCH_NAME
            git push origin $BRANCH_NAME
            
